name: Validate students.yaml (PR)

on:
  pull_request:
    branches: [ main ]
    paths:
      - "2025-fall/students.yaml"

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm i -D yaml-lint node-fetch@3
      - name: Lint YAML
        run: npx yaml-lint 2025-fall/students.yaml
      - name: Ping student sites (HEAD requests)
        run: node scripts/ping-students.mjs
