name: Wrap Lessons (i18n)

on:
 push:
  branches: [main]
  paths:
   - 'web-foundations/docs/lessons/**'
   - 'web-foundations/docs/_data/lessons.yml'
   - 'scripts/wrap-lessons.mjs'
 workflow_dispatch:

permissions:
 contents: write

jobs:
 wrap:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout (full history)
     uses: actions/checkout@v4
     with:
      fetch-depth: 0

   - name: Setup Node
     uses: actions/setup-node@v4
     with:
      node-version: '20'

   - name: Install wrap deps (no-save)
     run: |
      npm install --no-save gray-matter yaml glob fs-extra slugify

   - name: Run wrapper (generate ES/EN scaffolds + lessons index)
     run: node scripts/wrap-lessons.mjs

   # Optional: validate the YAML index after wrapping
   - name: Sanity check lessons index
     run: |
      node -e "const fs=require('fs'); const yaml=require('yaml'); const p='web-foundations/docs/_data/lessons.yml'; yaml.parse(fs.readFileSync(p,'utf8')); console.log('lessons.yml OK:', p)"

   # Auto-commit any generated/updated files
   - name: Auto-commit changes
     uses: stefanzweifel/git-auto-commit-action@v5
     with:
      commit_message: 'chore(i18n): wrap lessons (ES/EN scaffolds & index sync)'
      commit_user_name: 'atelier-udit-bot'
      commit_user_email: 'actions@github.com'
      branch: main
